# MailHog (https://github.com/mailhog/MailHog)
# docker run --rm -p 1025:1025 -p 8025:8025 mailhog/mailhog
# http://localhost:8025/
version: '3'

services:
  mailhog: # MailHog (https://github.com/mailhog/MailHog) --> http://localhost:8025/
    # docker run --rm -p 1025:1025 -p 8025:8025 mailhog/mailhog
    image: mailhog/mailhog
    ports:
      # SMTP port
      - "1025:1025"
      # Web port
      - "8025:8025"
