version: '3'

networks:
  keycloak:

services:
  keycloak:
    image: ${docker.registry}${project.groupId}.container:${project.version}
    container_name: ${project.groupId}.container
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - keycloak.common.env
      - keycloak.specific.env
      - secrets.env
    networks:
      - keycloak
    labels:
      org.labels-schema.group: "iam"
